var os=require('os');
console.log("Home Directory is: ",os.homedir());
console.log("Platform: "+os.platform());
console.log("Type of os: "+os.type());
console.log("Hostname: "+os.hostname());
console.log("Release Version: "+os.release());
console.log("Architecture: "+os.arch());
console.log("Total memory in bytes: "+os.totalmem());
console.log("Free memory in  bytes: "+os.freemem());
var c=os.cpus();
console.log("Total number of cpus:"+c.length);
console.log(c);
